export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const CHANGE_CONTROL_FILTER = 'CHANGE_CONTROL_FILTER';
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';