const TYPESFORUSER = {
  LOG_IN_USER: 'LOG_IN_USER',
  LOG_OUT_USER: 'LOG_OUT_USER'
};

const TYPEFORCONTROLPANEL = {
  CHANGE_CONTROL_FILTER: 'CHANGE_CONTROL_FILTER',
}

export { TYPESFORUSER, TYPEFORCONTROLPANEL };